// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/gamm/v1beta1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	PoolCreationFee           github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=pool_creation_fee,json=poolCreationFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"pool_creation_fee" yaml:"pool_creation_fee"`
	EnableGlobalPoolFees      bool                                     `protobuf:"varint,2,opt,name=enable_global_pool_fees,json=enableGlobalPoolFees,proto3" json:"enable_global_pool_fees,omitempty"`
	GlobalFees                GlobalFees                               `protobuf:"bytes,3,opt,name=global_fees,json=globalFees,proto3" json:"global_fees" yaml:"global_fees"`
	TakerFee                  cosmossdk_io_math.LegacyDec              `protobuf:"bytes,4,opt,name=taker_fee,json=takerFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"taker_fee" yaml:"taker_fee"`
	AllowedPoolCreationDenoms []string                                 `protobuf:"bytes,5,rep,name=allowed_pool_creation_denoms,json=allowedPoolCreationDenoms,proto3" json:"allowed_pool_creation_denoms,omitempty" yaml:"allowed_pool_creation_denoms"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f631bb2cb127d8, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPoolCreationFee() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.PoolCreationFee
	}
	return nil
}

func (m *Params) GetEnableGlobalPoolFees() bool {
	if m != nil {
		return m.EnableGlobalPoolFees
	}
	return false
}

func (m *Params) GetGlobalFees() GlobalFees {
	if m != nil {
		return m.GlobalFees
	}
	return GlobalFees{}
}

func (m *Params) GetAllowedPoolCreationDenoms() []string {
	if m != nil {
		return m.AllowedPoolCreationDenoms
	}
	return nil
}

type GlobalFees struct {
	SwapFee cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=swap_fee,json=swapFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"swap_fee" yaml:"swap_fee"`
	ExitFee cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=exit_fee,json=exitFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"exit_fee" yaml:"exit_fee"`
}

func (m *GlobalFees) Reset()         { *m = GlobalFees{} }
func (m *GlobalFees) String() string { return proto.CompactTextString(m) }
func (*GlobalFees) ProtoMessage()    {}
func (*GlobalFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2f631bb2cb127d8, []int{1}
}
func (m *GlobalFees) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GlobalFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GlobalFees.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GlobalFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalFees.Merge(m, src)
}
func (m *GlobalFees) XXX_Size() int {
	return m.Size()
}
func (m *GlobalFees) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalFees.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalFees proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "dymensionxyz.dymension.gamm.v1beta1.Params")
	proto.RegisterType((*GlobalFees)(nil), "dymensionxyz.dymension.gamm.v1beta1.GlobalFees")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/gamm/v1beta1/params.proto", fileDescriptor_f2f631bb2cb127d8)
}

var fileDescriptor_f2f631bb2cb127d8 = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0xdb, 0x52, 0xd2, 0xcd, 0xa1, 0x60, 0x55, 0x22, 0x09, 0xc8, 0x8e, 0xdc, 0x03, 0xbe,
	0x64, 0xb7, 0x29, 0xea, 0x85, 0x63, 0x1a, 0x82, 0x84, 0x7a, 0x88, 0x72, 0xe4, 0x62, 0xad, 0x9d,
	0x89, 0x63, 0x65, 0xed, 0x8d, 0xb2, 0x6e, 0x1b, 0xf3, 0x14, 0x20, 0xde, 0x82, 0x33, 0x0f, 0xd1,
	0x13, 0xaa, 0x38, 0x21, 0x0e, 0x01, 0x25, 0x6f, 0x90, 0x27, 0x40, 0xfb, 0x93, 0x10, 0xa8, 0x84,
	0x2a, 0x4e, 0xf6, 0xe8, 0x9b, 0xef, 0x9b, 0xf9, 0x3e, 0xcd, 0xa2, 0x93, 0x41, 0x91, 0x42, 0x26,
	0x12, 0x9e, 0xcd, 0x8a, 0x77, 0x64, 0x53, 0x90, 0x98, 0xa6, 0x29, 0xb9, 0x6a, 0x85, 0x90, 0xd3,
	0x16, 0x99, 0xd0, 0x29, 0x4d, 0x05, 0x9e, 0x4c, 0x79, 0xce, 0xed, 0xe3, 0x6d, 0x06, 0xde, 0x14,
	0x58, 0x32, 0xb0, 0x61, 0xd4, 0x8f, 0x62, 0x1e, 0x73, 0xd5, 0x4f, 0xe4, 0x9f, 0xa6, 0xd6, 0x6b,
	0x31, 0xe7, 0x31, 0x03, 0xa2, 0xaa, 0xf0, 0x72, 0x48, 0x68, 0x56, 0xac, 0xa1, 0x88, 0x8b, 0x94,
	0x8b, 0x40, 0x73, 0x74, 0x61, 0x20, 0x47, 0x57, 0x24, 0xa4, 0x02, 0x36, 0x2b, 0x45, 0x3c, 0xc9,
	0x34, 0xee, 0x7d, 0xd8, 0x43, 0xfb, 0x3d, 0xb5, 0xa1, 0xfd, 0xd1, 0x42, 0x8f, 0x27, 0x9c, 0xb3,
	0x20, 0x9a, 0x02, 0xcd, 0x13, 0x9e, 0x05, 0x43, 0x80, 0xaa, 0xd5, 0xd8, 0xf5, 0x2b, 0xa7, 0x35,
	0x6c, 0x54, 0xa5, 0xce, 0x7a, 0x51, 0x7c, 0xce, 0x93, 0xac, 0x7d, 0x71, 0x33, 0x77, 0x4b, 0xab,
	0xb9, 0x5b, 0x2d, 0x68, 0xca, 0x5e, 0x7a, 0x77, 0x14, 0xbc, 0x4f, 0x3f, 0x5c, 0x3f, 0x4e, 0xf2,
	0xd1, 0x65, 0x88, 0x23, 0x9e, 0x9a, 0xf5, 0xcc, 0xa7, 0x29, 0x06, 0x63, 0x92, 0x17, 0x13, 0x10,
	0x4a, 0x4c, 0xf4, 0x0f, 0x25, 0xff, 0xdc, 0xd0, 0xbb, 0x00, 0xf6, 0x19, 0x7a, 0x02, 0x19, 0x0d,
	0x19, 0x04, 0x31, 0xe3, 0x21, 0x65, 0x81, 0x1a, 0x30, 0x04, 0x10, 0xd5, 0x9d, 0x86, 0xe5, 0x97,
	0xfb, 0x47, 0x1a, 0x7e, 0xad, 0xd0, 0x1e, 0xe7, 0xac, 0x0b, 0x20, 0x6c, 0x86, 0x2a, 0xa6, 0x5f,
	0xb5, 0xee, 0x36, 0x2c, 0xbf, 0x72, 0x4a, 0xf0, 0x3d, 0xe2, 0xc7, 0x5a, 0x49, 0xaa, 0xb4, 0xeb,
	0xc6, 0x9b, 0xad, 0xbd, 0x6d, 0x29, 0x7a, 0x7d, 0x14, 0x6f, 0xfa, 0xec, 0x10, 0x1d, 0xe4, 0x74,
	0x0c, 0x53, 0x95, 0xd8, 0x5e, 0xc3, 0xf2, 0x0f, 0xda, 0xaf, 0x24, 0xf5, 0xfb, 0xdc, 0x7d, 0xaa,
	0x8d, 0x8a, 0xc1, 0x18, 0x27, 0x9c, 0xa4, 0x34, 0x1f, 0xe1, 0x0b, 0x88, 0x69, 0x54, 0x74, 0x20,
	0x5a, 0xcd, 0xdd, 0x47, 0x5a, 0x79, 0xc3, 0xf6, 0xbe, 0x7e, 0x6e, 0x22, 0x93, 0x75, 0x07, 0xa2,
	0x7e, 0x59, 0x21, 0x32, 0x88, 0x11, 0x7a, 0x46, 0x19, 0xe3, 0xd7, 0x30, 0x08, 0xfe, 0xcc, 0x78,
	0x00, 0x19, 0x4f, 0x45, 0xf5, 0x41, 0x63, 0xd7, 0x3f, 0x68, 0x3f, 0x5f, 0xcd, 0xdd, 0x63, 0xad,
	0xf9, 0xaf, 0x6e, 0xaf, 0x5f, 0x33, 0x70, 0x6f, 0x2b, 0xef, 0x8e, 0xc6, 0xbe, 0x58, 0x08, 0xfd,
	0x0e, 0xc1, 0x0e, 0x50, 0x59, 0x5c, 0xd3, 0x89, 0xb9, 0x06, 0xe9, 0xad, 0x73, 0x3f, 0x6f, 0x87,
	0x7a, 0x8f, 0x35, 0xf9, 0x6f, 0x6b, 0x0f, 0x25, 0x20, 0x9d, 0x05, 0xa8, 0x0c, 0xb3, 0x24, 0x57,
	0x03, 0x76, 0xfe, 0x63, 0xc0, 0x9a, 0x7c, 0x67, 0x80, 0x04, 0xba, 0x00, 0xed, 0x37, 0x37, 0x0b,
	0xc7, 0xba, 0x5d, 0x38, 0xd6, 0xcf, 0x85, 0x63, 0xbd, 0x5f, 0x3a, 0xa5, 0xdb, 0xa5, 0x53, 0xfa,
	0xb6, 0x74, 0x4a, 0x6f, 0x4f, 0xb6, 0x0e, 0x53, 0x11, 0x13, 0xd1, 0x64, 0x34, 0x14, 0xeb, 0x82,
	0x5c, 0xb5, 0xce, 0xc8, 0x4c, 0x3f, 0x68, 0x75, 0xa6, 0xe1, 0xbe, 0x7a, 0x37, 0x2f, 0x7e, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x4a, 0xc3, 0x7c, 0x0d, 0xfc, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowedPoolCreationDenoms) > 0 {
		for iNdEx := len(m.AllowedPoolCreationDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedPoolCreationDenoms[iNdEx])
			copy(dAtA[i:], m.AllowedPoolCreationDenoms[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AllowedPoolCreationDenoms[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size := m.TakerFee.Size()
		i -= size
		if _, err := m.TakerFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.GlobalFees.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.EnableGlobalPoolFees {
		i--
		if m.EnableGlobalPoolFees {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.PoolCreationFee) > 0 {
		for iNdEx := len(m.PoolCreationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolCreationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GlobalFees) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GlobalFees) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GlobalFees) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ExitFee.Size()
		i -= size
		if _, err := m.ExitFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.SwapFee.Size()
		i -= size
		if _, err := m.SwapFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PoolCreationFee) > 0 {
		for _, e := range m.PoolCreationFee {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.EnableGlobalPoolFees {
		n += 2
	}
	l = m.GlobalFees.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.TakerFee.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.AllowedPoolCreationDenoms) > 0 {
		for _, s := range m.AllowedPoolCreationDenoms {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *GlobalFees) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SwapFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.ExitFee.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolCreationFee = append(m.PoolCreationFee, types.Coin{})
			if err := m.PoolCreationFee[len(m.PoolCreationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableGlobalPoolFees", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableGlobalPoolFees = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GlobalFees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TakerFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedPoolCreationDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedPoolCreationDenoms = append(m.AllowedPoolCreationDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GlobalFees) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GlobalFees: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GlobalFees: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwapFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExitFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
