// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/txfees/v1beta1/feetoken.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/osmosis-labs/osmosis/v15/x/poolmanager/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FeeToken is a struct that specifies a coin denom, and pool ID pair.
// This marks the token as eligible for use as a tx fee asset in Osmosis.
// Its price in osmo is derived through looking at the provided pool ID.
// The pool ID must have base denom as one of its assets.
type FeeToken struct {
	Denom string                    `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty" yaml:"denom"`
	Route []types.SwapAmountInRoute `protobuf:"bytes,3,rep,name=route,proto3" json:"route" yaml:"route"`
}

func (m *FeeToken) Reset()         { *m = FeeToken{} }
func (m *FeeToken) String() string { return proto.CompactTextString(m) }
func (*FeeToken) ProtoMessage()    {}
func (*FeeToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca4a790beba5662b, []int{0}
}
func (m *FeeToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeToken.Merge(m, src)
}
func (m *FeeToken) XXX_Size() int {
	return m.Size()
}
func (m *FeeToken) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeToken.DiscardUnknown(m)
}

var xxx_messageInfo_FeeToken proto.InternalMessageInfo

func (m *FeeToken) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *FeeToken) GetRoute() []types.SwapAmountInRoute {
	if m != nil {
		return m.Route
	}
	return nil
}

func init() {
	proto.RegisterType((*FeeToken)(nil), "dymensionxyz.dymension.txfees.v1beta1.FeeToken")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/txfees/v1beta1/feetoken.proto", fileDescriptor_ca4a790beba5662b)
}

var fileDescriptor_ca4a790beba5662b = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x49, 0xa9, 0xcc, 0x4d,
	0xcd, 0x2b, 0xce, 0xcc, 0xcf, 0xab, 0xa8, 0xac, 0xd2, 0x87, 0x73, 0xf4, 0x4b, 0x2a, 0xd2, 0x52,
	0x53, 0x8b, 0xf5, 0xcb, 0x0c, 0x93, 0x52, 0x4b, 0x12, 0x0d, 0xf5, 0xd3, 0x52, 0x53, 0x4b, 0xf2,
	0xb3, 0x53, 0xf3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x54, 0x91, 0x75, 0xe9, 0xc1, 0x39,
	0x7a, 0x10, 0x5d, 0x7a, 0x50, 0x5d, 0x52, 0x22, 0xe9, 0xf9, 0xe9, 0xf9, 0x60, 0x1d, 0xfa, 0x20,
	0x16, 0x44, 0xb3, 0x94, 0x35, 0x0e, 0x2b, 0x0b, 0xf2, 0xf3, 0x73, 0x72, 0x13, 0xf3, 0x12, 0xd3,
	0x53, 0x8b, 0xe0, 0xf6, 0x16, 0x97, 0x27, 0x16, 0xc4, 0x17, 0xe5, 0x97, 0x96, 0xa4, 0x42, 0x34,
	0x2b, 0x2d, 0x66, 0xe4, 0xe2, 0x70, 0x4b, 0x4d, 0x0d, 0x01, 0x39, 0x46, 0x48, 0x8d, 0x8b, 0x35,
	0x25, 0x35, 0x2f, 0x3f, 0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0xd3, 0x49, 0xe0, 0xd3, 0x3d, 0x79,
	0x9e, 0xca, 0xc4, 0xdc, 0x1c, 0x2b, 0x25, 0xb0, 0xb0, 0x52, 0x10, 0x44, 0x5a, 0x28, 0x93, 0x8b,
	0x15, 0x6c, 0x86, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xad, 0x1e, 0x0e, 0xe7, 0x23, 0xb9,
	0x00, 0xe6, 0x07, 0xbd, 0xe0, 0xf2, 0xc4, 0x02, 0xc7, 0xdc, 0xfc, 0xd2, 0xbc, 0x12, 0xcf, 0xbc,
	0x20, 0x90, 0x21, 0x4e, 0x22, 0x27, 0xee, 0xc9, 0x33, 0x20, 0xac, 0x02, 0x9b, 0xac, 0x14, 0x04,
	0xb1, 0xc1, 0x8b, 0x85, 0x83, 0x49, 0x80, 0xd9, 0xc9, 0xe7, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f,
	0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b,
	0x8f, 0xe5, 0x18, 0xa2, 0x8c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5,
	0xf3, 0x8b, 0x73, 0xf3, 0x8b, 0x33, 0x8b, 0x75, 0x73, 0x12, 0x93, 0x8a, 0x61, 0x1c, 0xfd, 0x32,
	0x43, 0x53, 0xfd, 0x0a, 0x58, 0xf0, 0x97, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0xbd, 0x6e,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xc8, 0x81, 0x0b, 0xac, 0x01, 0x00, 0x00,
}

func (m *FeeToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Route) > 0 {
		for iNdEx := len(m.Route) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Route[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeetoken(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintFeetoken(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeetoken(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeetoken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovFeetoken(uint64(l))
	}
	if len(m.Route) > 0 {
		for _, e := range m.Route {
			l = e.Size()
			n += 1 + l + sovFeetoken(uint64(l))
		}
	}
	return n
}

func sovFeetoken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeetoken(x uint64) (n int) {
	return sovFeetoken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeetoken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeetoken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Route", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeetoken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeetoken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeetoken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Route = append(m.Route, types.SwapAmountInRoute{})
			if err := m.Route[len(m.Route)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeetoken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeetoken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeetoken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeetoken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeetoken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeetoken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeetoken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeetoken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeetoken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeetoken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeetoken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeetoken = fmt.Errorf("proto: unexpected end of group")
)
