syntax = "proto3";
package dymensionxyz.dymension.txfees.v1beta1;

import "gogoproto/gogo.proto";
import "dymensionxyz/dymension/poolmanager/v1beta1/swap_route.proto";

option go_package = "github.com/osmosis-labs/osmosis/v15/x/txfees/types";

// FeeToken is a struct that specifies a coin denom, and pool ID pair.
// This marks the token as eligible for use as a tx fee asset in Osmosis.
// Its price in osmo is derived through looking at the provided pool ID.
// The pool ID must have base denom as one of its assets.
message FeeToken {
  string denom = 1 [ (gogoproto.moretags) = "yaml:\"denom\"" ];

  reserved 2;

  repeated dymensionxyz.dymension.poolmanager.v1beta1.SwapAmountInRoute route =
      3
      [ (gogoproto.moretags) = "yaml:\"route\"", (gogoproto.nullable) = false ];
}