syntax = "proto3";
package dymensionxyz.dymension.txfees.v1beta1;

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "google/protobuf/duration.proto";
import "cosmos_proto/cosmos.proto";

import "dymensionxyz/dymension/txfees/v1beta1/feetoken.proto";
import "dymensionxyz/dymension/txfees/v1beta1/genesis.proto";
import "dymensionxyz/dymension/poolmanager/v1beta1/swap_route.proto";

option go_package = "github.com/osmosis-labs/osmosis/v15/x/txfees/types";

service Query {
  // Params returns params.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get =
        "/dymensionxyz/dymension/txfees/v1beta1/params";
  }

  // FeeToken returns a single fee token by denom
  rpc FeeToken(QueryFeeTokenRequest) returns (QueryFeeTokenResponse) {
    option (google.api.http).get =
        "/dymensionxyz/dymension/txfees/v1beta1/fee_tokens/{denom}";
  }

  // FeeTokens returns a list of all the accepted fee tokens and their
  // corresponding pools.
  // It does not include the BaseDenom, which has its own query endpoint
  rpc FeeTokens(QueryFeeTokensRequest) returns (QueryFeeTokensResponse) {
    option (google.api.http).get =
        "/dymensionxyz/dymension/txfees/v1beta1/fee_tokens";
  }

  // Returns the swap route for a specified denom
  rpc DenomRoute(QueryDenomRouteRequest) returns (QueryDenomRouteResponse) {
    option (google.api.http).get =
        "/dymensionxyz/dymension/txfees/v1beta1/denom_route/{denom}";
  }

  // Returns a list of all base denom tokens and their corresponding pools.
  rpc BaseDenom(QueryBaseDenomRequest) returns (QueryBaseDenomResponse) {
    option (google.api.http).get =
        "/dymensionxyz/dymension/txfees/v1beta1/base_denom";
  }
}

message QueryParamsRequest {}
message QueryParamsResponse {
  Params params = 1 [ (gogoproto.nullable) = false ];
}

message QueryFeeTokenRequest { string denom = 1; }

message QueryFeeTokenResponse {
  FeeToken fee_token = 1 [ (gogoproto.nullable) = false ];
}

message QueryFeeTokensRequest {}
message QueryFeeTokensResponse {
  repeated FeeToken fee_tokens = 1 [
    (gogoproto.moretags) = "yaml:\"fee_tokens\"",
    (gogoproto.nullable) = false
  ];
}

message QueryDenomRouteRequest { string denom = 1; }

message QueryDenomRouteResponse {
  repeated poolmanager.v1beta1.SwapAmountInRoute route = 1
      [ (gogoproto.nullable) = false ];
}

message QueryDenomPoolIdRequest {
  string denom = 1 [ (gogoproto.moretags) = "yaml:\"denom\"" ];
}
message QueryDenomPoolIdResponse {
  uint64 poolID = 1 [ (gogoproto.moretags) = "yaml:\"pool_id\"" ];
}

message QueryBaseDenomRequest {}
message QueryBaseDenomResponse {
  string base_denom = 1 [ (gogoproto.moretags) = "yaml:\"base_denom\"" ];
}
